"""base

Revision ID: 63ad6a0c29b4
Revises: 
Create Date: 2023-09-08 06:35:45.354758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ad6a0c29b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('favorite_subject', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teachers_table'))
    )
    op.create_table('students_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('favorite_subject', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers_table.id'], name=op.f('fk_students_table_teacher_id_teachers_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students_table'))
    )
    op.drop_table('birds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('species', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='birds_pkey')
    )
    op.drop_table('students_table')
    op.drop_table('teachers_table')
    # ### end Alembic commands ###
